services:
  web:
    build: .
    image: giuliomastromartino/basketball-stats:latest
    ports:
      - "8080:8080"
    volumes:
      # Mount the instance folder for persistent database storage
      # Ensure your flask config uses 'sqlite:///instance/database.db'
      - ./instance:/app/instance
    restart: unless-stopped
